# Generated by Django 3.1.6 on 2021-03-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('height', models.DecimalField(decimal_places=1, max_digits=1)),
                ('time', models.DecimalField(decimal_places=0, max_digits=4)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
