# Generated by Django 3.1.6 on 2021-03-29 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='User',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
