# Generated by Django 3.1.6 on 2021-04-06 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_dashboard_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='Workout_Goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=4), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='Workout_Name',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='Workout_Progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=4), size=None), size=None),
        ),
    ]
