# Generated by Django 3.1.6 on 2021-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_auto_20210406_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
