# Generated by Django 3.1.6 on 2021-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_auto_20210417_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ThumbsUp',
            field=models.IntegerField(default=0),
        ),
    ]
