# Generated by Django 3.1.7 on 2021-05-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_profile_thumbsup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
